### ISSUE TITLE
Lulu upload error with JXL

### ISSUE THREAD

**Issue by mvahowe** [mvh-solutions/jxl-pdf#14]
[tit_php_fr.pdf](https://github.com/mvh-solutions/jxl-pdf/files/13922815/tit_php_fr.pdf)
![upload_error](https://github.com/mvh-solutions/jxl-pdf/assets/1576594/f6c382a9-f652-42dc-b67d-b005e1f3d808)

**Comment by DanielC-N** [comment]
I've tested it myself with various pdfs.
What I've understood is that the "compressed" version works every time, while the normal `generated_output` works *sometimes*.

I'd recommend using every time the compressed generated output. Until make the code always generate the compressed version by default.

**Comment by DanielC-N** [comment]
btw. It's uploading for the compressed version but :
![image](https://github.com/mvh-solutions/jxl-pdf/assets/18301757/ba25e6ac-2177-479a-8e25-30eb921da8e0)

**Comment by DanielC-N** [comment]
nvm. I've just found a counter example, with a compressed file that doesn't work too.
