### ISSUE TITLE
"Cut and Assemble" solution for double-page spread layouts

### ISSUE THREAD

**Issue by mvahowe** [mvh-solutions/jxl-pdf#3]
- Take a PDF containing one or more double-spread landscape pages
- Return a PDF containing each of those double-spread pages as a verso and a recto portrait page

Consider using pyPDF as CLI script or behind flask.

**Comment by mvahowe** [comment]
Also need to add page numbers

**Comment by DanielC-N** [comment]
4a2e2e112c49c7e9f28ece9b59b25e6c5cf5729c
